# Generated by Django 4.1 on 2022-08-31 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Libro',
            new_name='Book',
        ),
    ]
